### ISSUE TITLE
Can't Fetch Forge Versions

### ISSUE THREAD

**Issue by myleskeeffe** [TheGameSpider/TechnicSolder#17]
**Describe the bug**
In the Forge Versions tab of the website no matter what I do I cannot get any versions to show up. When using the built in tool to fetch versions, it gets stuck on a spinning cog without doing anything. The file is created, but even upon refresh will not showup in the website. When fetching again, you get the file already exists error message. 

I have also tried by downloading forge myself and uploading it as modpack.jar, which also works and uploads correctly - but does not show up in the website as uploaded.

**To Reproduce**
1. Go to "Forge Versions" Tab
2. Click "Fetch Forge Versions"
3. Click "Add To Database" on a version of choice (for instance 1.12.2)
4. Observe a spinning cog of death
5. Reload page after a couple mins, and notice how forge version isn't listed & you cannot download it again

**Expected behavior**
I expect the forge version to download & show up in the web interface

**Screenshots**
![image](https://user-images.githubusercontent.com/11828103/77843186-5403f000-71cd-11ea-9a94-aed2f8dcf912.png)

**Comment by myleskeeffe** [comment]
Quick Update: I've done some more prodding and found that the post request it sends come back with an error 500 (internal server error). I also tries dragging and dropping mod jaws into the mod library, and the exact same error occurred.

**Comment by TheGameSpider** [comment]
This problem happens when you try to import any mods/forges and you don't
have the zip extension installed. Install the PHP zip extension and try
again.

Dňa ne, 29. mar 2020, 11:46 Pikles <notifications@github.com> napísal(a):

**Comment by myleskeeffe** [comment]
Awesome - totally glossed over that part in the install guide (I skipped past the setup a webserver section as I already have an nginx server setup - probably should read that if I have trouble next time). Thankyou so much!
