### ISSUE TITLE
Subdirectory Installation

### ISSUE THREAD

**Issue by Rustypredator** [TheGameSpider/TechnicSolder#2]
Please add Automatic detection whether the install is in an Subdirectory.
That way you can stop fiddling with the host.conf and even install your solder in a subdirectory on an already existing host.

Would be pretty easy to implement by using a custom ```redirect("target")``` function rather than the ```header("Location: target")``` function directly, and using the root dir in this function. If you need help implementing that, just pm me.

**Comment by TheGameSpider** [comment]
Fixed

**Comment by Prasodym** [comment]
![Unbenannvt](https://user-images.githubusercontent.com/38152214/80911209-4a722880-8d35-11ea-988e-aa2ab9f69917.PNG)
So with me, there's no way
