### ISSUE TITLE
Password Encryption?

### ISSUE THREAD

**Issue by SCPDR-Erin** [TheGameSpider/TechnicSolder#9]
It's a small thing and probably useless, but it'd be an alright idea to actually have the passwords stored on a DB to be encrypted. 

As I said before it's probably useless :p

**Comment by benglvr** [comment]
Not useless at all, this is a serious security vulnerability. Passwords should always be encrypted.

**Comment by TheGameSpider** [comment]
Fixed in v1.3.0

**Comment by Kio-td** [comment]
This issue is still a valid issue, because Passwords, while encrypted, use a baseline salt, leaving passwords open to Rainbow Tables (See https://xkcd.com/1286/ )
